# Generated by Django 4.2.2 on 2023-06-25 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FlightWebsite', '0002_remove_flight_arrival_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='departure_time',
        ),
    ]
